/* Fargo: Character Connections
 * Data sourced from the Fargo Fandom wiki: https://fargo.fandom.com/wiki/Fargo_(TV_series)
 * Each season is self-contained: a list of characters (with portrait image URLs)
 * and a list of directed connections between them (relationships, killings, etc).
 */
window.FARGO_DATA = {
  seasons: [
    {
      season: 1,
      title: "Season One",
      year: "2014",
      blurb: "Bemidji and Duluth, Minnesota, where a drifter's chaos meets a meek insurance man.",
      characters: [
        { id: "s1-lorne-malvo", name: "Lorne Malvo", actor: "Billy Bob Thornton", role: "Manipulative drifter and hitman who sows chaos across Minnesota", group: "Killers / outsiders", image: "https://static.wikia.nocookie.net/fargo/images/e/e9/Lorne_Malvo_%282007%29.jpg/revision/latest?cb=20260318124548" },
        { id: "s1-lester-nygaard", name: "Lester Nygaard", actor: "Martin Freeman", role: "Henpecked insurance salesman turned killer", group: "Nygaard / civilians", image: "https://static.wikia.nocookie.net/fargo/images/5/54/Lester_Nygaard_%282007%29.jpg/revision/latest?cb=20260318124918" },
        { id: "s1-molly-solverson", name: "Molly Solverson", actor: "Allison Tolman", role: "Dogged Bemidji deputy investigating the murders", group: "Bemidji police", image: "https://static.wikia.nocookie.net/fargo/images/6/62/Molly_Solverson_%282007%29.png/revision/latest?cb=20260224135043" },
        { id: "s1-gus-grimly", name: "Gus Grimly", actor: "Colin Hanks", role: "Duluth officer turned mailman; Molly's ally and love interest", group: "Duluth police", image: "https://static.wikia.nocookie.net/fargo/images/b/b1/Gus_Grimly_%282006%29.jpg/revision/latest?cb=20260317134240" },
        { id: "s1-bill-oswalt", name: "Bill Oswalt", actor: "Bob Odenkirk", role: "Naive Bemidji police chief who doubts Molly's theory", group: "Bemidji police", image: "https://static.wikia.nocookie.net/fargo/images/9/90/Bill_Oswalt_%282006%29.jpg/revision/latest?cb=20260601121528" },
        { id: "s1-vern-thurman", name: "Vern Thurman", actor: "Shawn Doyle", role: "Bemidji police chief murdered early by Malvo", group: "Bemidji police", image: "https://static.wikia.nocookie.net/fargo/images/1/1b/VernThurman.png/revision/latest?cb=20180819071902" },
        { id: "s1-lou-solverson", name: "Lou Solverson", actor: "Keith Carradine", role: "Former state trooper, diner owner, and Molly's father", group: "Bemidji police", image: "https://static.wikia.nocookie.net/fargo/images/8/88/Lou_Solverson_%282007%29.jpg/revision/latest?cb=20260224141402" },
        { id: "s1-sam-hess", name: "Sam Hess", actor: "Kevin O'Grady", role: "Trucking-firm owner and Lester's childhood bully, killed by Malvo", group: "Nygaard / civilians", image: "https://static.wikia.nocookie.net/fargo/images/d/d5/SamHess.png/revision/latest?cb=20180819072332" },
        { id: "s1-gina-hess", name: "Gina Hess", actor: "Kate Walsh", role: "Sam's brash widow chasing his insurance payout", group: "Nygaard / civilians", image: "https://static.wikia.nocookie.net/fargo/images/9/9a/Gina.png/revision/latest?cb=20140428194921" },
        { id: "s1-pearl-nygaard", name: "Pearl Nygaard", actor: "Kelly Holden Bashar", role: "Lester's belittling wife, killed by him with a hammer", group: "Nygaard / civilians", image: "https://static.wikia.nocookie.net/fargo/images/c/c7/Mrsnygaard.png/revision/latest?cb=20140423052320" },
        { id: "s1-chazz-nygaard", name: "Chazz Nygaard", actor: "Josh Close", role: "Lester's smug, more successful younger brother, framed for murder", group: "Nygaard / civilians", image: "https://static.wikia.nocookie.net/fargo/images/4/4d/Chaz.png/revision/latest?cb=20140428203812" },
        { id: "s1-stavros-milos", name: "Stavros Milos", actor: "Oliver Platt", role: "Religious supermarket tycoon extorted by Malvo", group: "Milos / extortion plot", image: "https://static.wikia.nocookie.net/fargo/images/1/14/StavrosEpisode6.png/revision/latest?cb=20180806195735" },
        { id: "s1-don-chumph", name: "Don Chumph", actor: "Glenn Howerton", role: "Personal trainer and Malvo's bumbling accomplice in the extortion scheme", group: "Milos / extortion plot", image: "https://static.wikia.nocookie.net/fargo/images/e/e4/DonC.png/revision/latest?cb=20180806170841" },
        { id: "s1-mr-wrench", name: "Mr. Wrench", actor: "Russell Harvard", role: "Deaf Fargo-syndicate hitman hunting Hess's killer", group: "Fargo syndicate", image: "https://static.wikia.nocookie.net/fargo/images/3/32/Wrench.jpg/revision/latest?cb=20140430012616" },
        { id: "s1-mr-numbers", name: "Mr. Numbers", actor: "Adam Goldberg", role: "Fargo-syndicate hitman and Wrench's partner", group: "Fargo syndicate", image: "https://static.wikia.nocookie.net/fargo/images/2/2c/Numbers_Wrench.png/revision/latest?cb=20201122011913" },
        { id: "s1-greta-grimly", name: "Greta Grimly", actor: "Joey King", role: "Gus's perceptive teenage daughter", group: "Duluth police", image: "https://static.wikia.nocookie.net/fargo/images/d/d8/Greta.jpg/revision/latest?cb=20200509041933" }
      ],
      connections: [
        { source: "s1-lorne-malvo", target: "s1-lester-nygaard", label: "manipulates" },
        { source: "s1-lester-nygaard", target: "s1-sam-hess", label: "wishes dead to" },
        { source: "s1-lorne-malvo", target: "s1-sam-hess", label: "kills" },
        { source: "s1-lester-nygaard", target: "s1-pearl-nygaard", label: "kills" },
        { source: "s1-pearl-nygaard", target: "s1-lester-nygaard", label: "wife of" },
        { source: "s1-chazz-nygaard", target: "s1-lester-nygaard", label: "brother of" },
        { source: "s1-lester-nygaard", target: "s1-chazz-nygaard", label: "frames" },
        { source: "s1-lorne-malvo", target: "s1-vern-thurman", label: "kills" },
        { source: "s1-vern-thurman", target: "s1-molly-solverson", label: "mentors" },
        { source: "s1-molly-solverson", target: "s1-lester-nygaard", label: "investigates" },
        { source: "s1-molly-solverson", target: "s1-lorne-malvo", label: "investigates" },
        { source: "s1-bill-oswalt", target: "s1-molly-solverson", label: "supervises" },
        { source: "s1-gus-grimly", target: "s1-lorne-malvo", label: "lets go, later shoots" },
        { source: "s1-gus-grimly", target: "s1-molly-solverson", label: "partner of" },
        { source: "s1-gus-grimly", target: "s1-greta-grimly", label: "father of" },
        { source: "s1-lou-solverson", target: "s1-molly-solverson", label: "father of" },
        { source: "s1-gina-hess", target: "s1-sam-hess", label: "widow of" },
        { source: "s1-gina-hess", target: "s1-lester-nygaard", label: "seeks payout from" },
        { source: "s1-lorne-malvo", target: "s1-stavros-milos", label: "extorts" },
        { source: "s1-don-chumph", target: "s1-lorne-malvo", label: "assists" },
        { source: "s1-lorne-malvo", target: "s1-don-chumph", label: "kills" },
        { source: "s1-don-chumph", target: "s1-stavros-milos", label: "trainer of" },
        { source: "s1-mr-numbers", target: "s1-mr-wrench", label: "partner of" },
        { source: "s1-mr-wrench", target: "s1-lester-nygaard", label: "hunts" },
        { source: "s1-mr-numbers", target: "s1-sam-hess", label: "avenges" },
        { source: "s1-lorne-malvo", target: "s1-mr-numbers", label: "kills" }
      ]
    },
    {
      season: 2,
      title: "Season Two",
      year: "2015",
      blurb: "In 1979, around Luverne and Fargo, the Gerhardt crime family wars with Kansas City.",
      characters: [
        { id: "s2-lou-solverson", name: "Lou Solverson", actor: "Patrick Wilson", role: "Minnesota State Trooper", group: "Law", image: "https://static.wikia.nocookie.net/fargo/images/1/1f/Lou_Solverson_%281979%29.jpg/revision/latest?cb=20260224141433" },
        { id: "s2-betsy-solverson", name: "Betsy Solverson", actor: "Cristin Milioti", role: "Lou's wife, battling cancer", group: "Law", image: "https://static.wikia.nocookie.net/fargo/images/e/ec/Betsy.png/revision/latest?cb=20170319035718" },
        { id: "s2-hank-larsson", name: "Hank Larsson", actor: "Ted Danson", role: "Rock County Sheriff and Betsy's father", group: "Law", image: "https://static.wikia.nocookie.net/fargo/images/9/9f/Hank_larsson.png/revision/latest?cb=20150721231443" },
        { id: "s2-ed-blumquist", name: "Ed Blumquist", actor: "Jesse Plemons", role: "Luverne butcher caught up in a hit-and-run cover-up", group: "Blumquist", image: "https://static.wikia.nocookie.net/fargo/images/1/19/EdEpisode5.png/revision/latest?cb=20180807223644" },
        { id: "s2-peggy-blumquist", name: "Peggy Blumquist", actor: "Kirsten Dunst", role: "Hairdresser dreaming of self-actualization", group: "Blumquist", image: "https://static.wikia.nocookie.net/fargo/images/2/2d/PeggyEpisode6.png/revision/latest?cb=20180807234056" },
        { id: "s2-floyd-gerhardt", name: "Floyd Gerhardt", actor: "Jean Smart", role: "Gerhardt matriarch / crime boss", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/9/98/Floyd.png/revision/latest?cb=20150721232054" },
        { id: "s2-otto-gerhardt", name: "Otto Gerhardt", actor: "Michael Hogan", role: "Gerhardt patriarch felled by a stroke", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/f/f6/Otto.png/revision/latest?cb=20151021231957" },
        { id: "s2-dodd-gerhardt", name: "Dodd Gerhardt", actor: "Jeffery Donovan", role: "Volatile eldest Gerhardt son", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/c/c5/DoddEpisode4.png/revision/latest?cb=20180807213836" },
        { id: "s2-bear-gerhardt", name: "Bear Gerhardt", actor: "Angus Sampson", role: "Level-headed middle Gerhardt son", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/d/d7/BearEpisode7.png/revision/latest?cb=20180807234451" },
        { id: "s2-rye-gerhardt", name: "Rye Gerhardt", actor: "Kieran Culkin", role: "Reckless youngest Gerhardt son", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/e/e1/Gerhardt_rye.jpg/revision/latest?cb=20200507203715" },
        { id: "s2-simone-gerhardt", name: "Simone Gerhardt", actor: "Rachel Keller", role: "Dodd's rebellious daughter", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/a/a1/SimoneEpisode3.png/revision/latest?cb=20180807213515" },
        { id: "s2-hanzee-dent", name: "Hanzee Dent", actor: "Zahn McClarnon", role: "Gerhardt enforcer and tracker", group: "Gerhardt", image: "https://static.wikia.nocookie.net/fargo/images/b/be/Hanzee_Dent_%281979%29.jpg/revision/latest?cb=20260313135807" },
        { id: "s2-mike-milligan", name: "Mike Milligan", actor: "Bokeem Woodbine", role: "Silver-tongued Kansas City mob enforcer", group: "Kansas City", image: "https://static.wikia.nocookie.net/fargo/images/a/ae/MikeEpisode7.png/revision/latest?cb=20180807215642" },
        { id: "s2-joe-bulo", name: "Joe Bulo", actor: "Brad Garrett", role: "Kansas City mob middle manager", group: "Kansas City", image: "https://static.wikia.nocookie.net/fargo/images/3/39/Joebulo.png/revision/latest?cb=20151123225856" },
        { id: "s2-gale-kitchen", name: "Gale Kitchen", actor: "Brad Mann", role: "Kansas City hitman (one of the Kitchen Brothers)", group: "Kansas City", image: "https://static.wikia.nocookie.net/fargo/images/8/85/GaleKitchenEpisode5.png/revision/latest?cb=20180807195621" },
        { id: "s2-karl-weathers", name: "Karl Weathers", actor: "Nick Offerman", role: "Loquacious small-town lawyer", group: "Luverne", image: "https://static.wikia.nocookie.net/fargo/images/c/c7/Karl_Weathers.jpg/revision/latest?cb=20151002004615" },
        { id: "s2-ben-schmidt", name: "Ben Schmidt", actor: "Keir O'Donnell", role: "Fargo police officer", group: "Law", image: "https://static.wikia.nocookie.net/fargo/images/b/b3/Ben_Schmidt.jpg/revision/latest?cb=20200507141859" },
        { id: "s2-constance-heck", name: "Constance Heck", actor: "Elizabeth Marvel", role: "Peggy's salon coworker", group: "Luverne", image: "https://static.wikia.nocookie.net/fargo/images/9/9f/Constance_Heck.jpg/revision/latest?cb=20170403185210" }
      ],
      connections: [
        { source: "s2-otto-gerhardt", target: "s2-floyd-gerhardt", label: "husband of" },
        { source: "s2-dodd-gerhardt", target: "s2-otto-gerhardt", label: "son of" },
        { source: "s2-dodd-gerhardt", target: "s2-floyd-gerhardt", label: "son of" },
        { source: "s2-bear-gerhardt", target: "s2-otto-gerhardt", label: "son of" },
        { source: "s2-bear-gerhardt", target: "s2-floyd-gerhardt", label: "son of" },
        { source: "s2-rye-gerhardt", target: "s2-otto-gerhardt", label: "son of" },
        { source: "s2-rye-gerhardt", target: "s2-floyd-gerhardt", label: "son of" },
        { source: "s2-simone-gerhardt", target: "s2-dodd-gerhardt", label: "daughter of" },
        { source: "s2-floyd-gerhardt", target: "s2-otto-gerhardt", label: "takes over for ailing" },
        { source: "s2-hanzee-dent", target: "s2-dodd-gerhardt", label: "enforcer for" },
        { source: "s2-hanzee-dent", target: "s2-floyd-gerhardt", label: "raised by" },
        { source: "s2-hanzee-dent", target: "s2-dodd-gerhardt", label: "kills" },
        { source: "s2-simone-gerhardt", target: "s2-mike-milligan", label: "informs to" },
        { source: "s2-bear-gerhardt", target: "s2-simone-gerhardt", label: "kills" },
        { source: "s2-mike-milligan", target: "s2-joe-bulo", label: "enforcer for" },
        { source: "s2-gale-kitchen", target: "s2-mike-milligan", label: "works with" },
        { source: "s2-joe-bulo", target: "s2-floyd-gerhardt", label: "moves on territory of" },
        { source: "s2-hanzee-dent", target: "s2-joe-bulo", label: "decapitates" },
        { source: "s2-mike-milligan", target: "s2-bear-gerhardt", label: "kills" },
        { source: "s2-rye-gerhardt", target: "s2-constance-heck", label: "kills" },
        { source: "s2-ed-blumquist", target: "s2-rye-gerhardt", label: "kills" },
        { source: "s2-peggy-blumquist", target: "s2-rye-gerhardt", label: "hits with car" },
        { source: "s2-peggy-blumquist", target: "s2-ed-blumquist", label: "wife of" },
        { source: "s2-ed-blumquist", target: "s2-dodd-gerhardt", label: "abducted by" },
        { source: "s2-constance-heck", target: "s2-peggy-blumquist", label: "coworker of" },
        { source: "s2-lou-solverson", target: "s2-betsy-solverson", label: "husband of" },
        { source: "s2-betsy-solverson", target: "s2-hank-larsson", label: "daughter of" },
        { source: "s2-lou-solverson", target: "s2-hank-larsson", label: "son-in-law of" },
        { source: "s2-hank-larsson", target: "s2-rye-gerhardt", label: "investigates murders by" },
        { source: "s2-lou-solverson", target: "s2-mike-milligan", label: "pursues" },
        { source: "s2-lou-solverson", target: "s2-ed-blumquist", label: "protects" },
        { source: "s2-karl-weathers", target: "s2-ed-blumquist", label: "defends" },
        { source: "s2-ben-schmidt", target: "s2-lou-solverson", label: "works case with" }
      ]
    },
    {
      season: 3,
      title: "Season Three",
      year: "2017",
      blurb: "In 2010, Eden Valley is caught between feuding Stussy brothers and a faceless corporate predator.",
      characters: [
        { id: "s3-emmit-stussy", name: "Emmit Stussy", actor: "Ewan McGregor", role: "The Parking Lot King of Minnesota", group: "Stussy", image: "https://static.wikia.nocookie.net/fargo/images/c/c1/Emmitstussy.png/revision/latest?cb=20170319030754" },
        { id: "s3-ray-stussy", name: "Ray Stussy", actor: "Ewan McGregor", role: "Resentful parole officer and Emmit's brother", group: "Stussy", image: "https://static.wikia.nocookie.net/fargo/images/1/1a/Ray_Stussy_%282010%29.jpg/revision/latest?cb=20260404130157" },
        { id: "s3-nikki-swango", name: "Nikki Swango", actor: "Mary Elizabeth Winstead", role: "Parolee, competitive bridge player, Ray's fiancée", group: "Stussy", image: "https://static.wikia.nocookie.net/fargo/images/1/15/Nikki_Swango.jpg/revision/latest?cb=20260421124521" },
        { id: "s3-vm-varga", name: "V.M. Varga", actor: "David Thewlis", role: "Mysterious capitalist and criminal mastermind", group: "Narwhal", image: "https://static.wikia.nocookie.net/fargo/images/d/d4/VM_Varga.jpg/revision/latest?cb=20260330142402" },
        { id: "s3-gloria-burgle", name: "Gloria Burgle", actor: "Carrie Coon", role: "Eden Valley Police Chief", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/c/c4/Gloria_Burgle_%282011%29.jpg/revision/latest?cb=20260420132923" },
        { id: "s3-sy-feltz", name: "Sy Feltz", actor: "Michael Stuhlbarg", role: "Emmit's anxious business partner", group: "Stussy", image: "https://static.wikia.nocookie.net/fargo/images/2/27/Syfeltz.png/revision/latest?cb=20170322235144" },
        { id: "s3-maurice-lefay", name: "Maurice LeFay", actor: "Scoot McNairy", role: "Stoner ex-con and parolee", group: "Criminals", image: "https://static.wikia.nocookie.net/fargo/images/3/30/MauriceLeFaySeason3Episode1.png/revision/latest?cb=20180808084852" },
        { id: "s3-yuri-gurka", name: "Yuri Gurka", actor: "Goran Bogdan", role: "Varga's brutal Cossack henchman", group: "Narwhal", image: "https://static.wikia.nocookie.net/fargo/images/c/cc/Yuri.png/revision/latest?cb=20170319030757" },
        { id: "s3-meemo", name: "Meemo", actor: "Andy Yu", role: "Varga's coolly efficient henchman", group: "Narwhal", image: "https://static.wikia.nocookie.net/fargo/images/2/25/Meemo.png/revision/latest?cb=20170319030757" },
        { id: "s3-winnie-lopez", name: "Winnie Lopez", actor: "Olivia Sandoval", role: "St. Cloud police officer who aids Gloria", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/a/a5/Winnie.jpg/revision/latest?cb=20170526014633" },
        { id: "s3-donny-mashman", name: "Donny Mashman", actor: "Mark Forward", role: "Eden Valley police officer", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/5/54/Donny_Mashman.jpg/revision/latest?cb=20170427202139" },
        { id: "s3-ennis-stussy", name: "Ennis Stussy", actor: "Scott Hylands", role: "Gloria's stepfather, killed in a mistaken-identity hit", group: "Law enforcement", image: null },
        { id: "s3-moe-dammick", name: "Moe Dammick", actor: "Shea Whigham", role: "St. Cloud Police Chief", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/0/09/MoeDammickSeason3Episode7.png/revision/latest?cb=20180808100234" }
      ],
      connections: [
        { source: "s3-emmit-stussy", target: "s3-ray-stussy", label: "brother of" },
        { source: "s3-ray-stussy", target: "s3-emmit-stussy", label: "resents and blames" },
        { source: "s3-ray-stussy", target: "s3-nikki-swango", label: "fiancé of" },
        { source: "s3-ray-stussy", target: "s3-maurice-lefay", label: "parole officer of" },
        { source: "s3-ray-stussy", target: "s3-maurice-lefay", label: "hires to steal stamp" },
        { source: "s3-maurice-lefay", target: "s3-ennis-stussy", label: "kills (wrong house)" },
        { source: "s3-nikki-swango", target: "s3-maurice-lefay", label: "kills" },
        { source: "s3-emmit-stussy", target: "s3-sy-feltz", label: "business partner of" },
        { source: "s3-vm-varga", target: "s3-emmit-stussy", label: "forces partnership on" },
        { source: "s3-vm-varga", target: "s3-yuri-gurka", label: "employs as henchman" },
        { source: "s3-vm-varga", target: "s3-meemo", label: "employs as henchman" },
        { source: "s3-yuri-gurka", target: "s3-meemo", label: "partner in crime" },
        { source: "s3-emmit-stussy", target: "s3-ray-stussy", label: "kills in argument" },
        { source: "s3-vm-varga", target: "s3-sy-feltz", label: "poisons" },
        { source: "s3-gloria-burgle", target: "s3-ennis-stussy", label: "stepdaughter of" },
        { source: "s3-gloria-burgle", target: "s3-maurice-lefay", label: "investigates" },
        { source: "s3-gloria-burgle", target: "s3-emmit-stussy", label: "investigates" },
        { source: "s3-gloria-burgle", target: "s3-vm-varga", label: "pursues" },
        { source: "s3-winnie-lopez", target: "s3-gloria-burgle", label: "partners with" },
        { source: "s3-donny-mashman", target: "s3-gloria-burgle", label: "deputy under" },
        { source: "s3-moe-dammick", target: "s3-gloria-burgle", label: "supervises" },
        { source: "s3-nikki-swango", target: "s3-emmit-stussy", label: "seeks revenge against" },
        { source: "s3-nikki-swango", target: "s3-vm-varga", label: "extorts and battles" },
        { source: "s3-yuri-gurka", target: "s3-nikki-swango", label: "hunts and attacks" },
        { source: "s3-gloria-burgle", target: "s3-nikki-swango", label: "investigates" }
      ]
    },
    {
      season: 4,
      title: "Season Four",
      year: "2020",
      blurb: "In 1950s Kansas City, two crime syndicates trade sons to keep an uneasy peace.",
      characters: [
        { id: "s4-loy-cannon", name: "Loy Cannon", actor: "Chris Rock", role: "Head of the Cannon Limited crime syndicate", group: "Cannon Limited", image: "https://static.wikia.nocookie.net/fargo/images/6/69/Loy_Cannon_in_Season_4%2C_Episode_1.jpg/revision/latest?cb=20200928085747" },
        { id: "s4-doctor-senator", name: "Doctor Senator", actor: "Glynn Turman", role: "Loy's closest advisor and second-in-command", group: "Cannon Limited", image: "https://static.wikia.nocookie.net/fargo/images/7/70/Doctor_Senator_in_Season_4%2C_Episode_1.jpg/revision/latest?cb=20200928090947" },
        { id: "s4-leon-bittle", name: "Leon Bittle", actor: "Jeremie Harris", role: "Ambitious young lieutenant in the Cannon syndicate", group: "Cannon Limited", image: "https://static.wikia.nocookie.net/fargo/images/3/3e/Leon_Bittle.jpg/revision/latest?cb=20200916192716" },
        { id: "s4-omie-sparkman", name: "Omie Sparkman", actor: "Corey Hendrix", role: "Cannon syndicate enforcer and right-hand man", group: "Cannon Limited", image: "https://static.wikia.nocookie.net/fargo/images/a/aa/Omie_Sparkman.jpg/revision/latest?cb=20200916193035" },
        { id: "s4-buel-cannon", name: "Buel Cannon", actor: "J. Nicole Brooks", role: "Loy Cannon's wife", group: "Cannon family", image: "https://static.wikia.nocookie.net/fargo/images/a/ab/BuelCannon.png/revision/latest?cb=20201108161454" },
        { id: "s4-lemuel-cannon", name: "Lemuel Cannon", actor: "Matthew Elam", role: "Loy and Buel's eldest son, an aspiring musician", group: "Cannon family", image: "https://static.wikia.nocookie.net/fargo/images/e/ee/Lemuel_Cannon.jpg/revision/latest?cb=20200916193631" },
        { id: "s4-satchel-cannon", name: "Satchel Cannon", actor: "Rodney L. Jones III", role: "Loy's young son, traded to the Faddas (the future Mike Milligan)", group: "Cannon family", image: null },
        { id: "s4-josto-fadda", name: "Josto Fadda", actor: "Jason Schwartzman", role: "Head of the Fadda crime family after Donatello's death", group: "Fadda family", image: "https://static.wikia.nocookie.net/fargo/images/2/28/Josto_Fadda.jpg/revision/latest?cb=20200916193740" },
        { id: "s4-gaetano-fadda", name: "Gaetano Fadda", actor: "Salvatore Esposito", role: "Josto's brutal younger brother, returned from Italy", group: "Fadda family", image: "https://static.wikia.nocookie.net/fargo/images/8/84/Gaetano_Fadda.jpg/revision/latest?cb=20200916193847" },
        { id: "s4-donatello-fadda", name: "Donatello Fadda", actor: "Tommaso Ragno", role: "Patriarch of the Fadda family; dies after surgery", group: "Fadda family", image: "https://static.wikia.nocookie.net/fargo/images/5/51/Don_Fadda.jpg/revision/latest?cb=20201009030651" },
        { id: "s4-ebal-violante", name: "Ebal Violante", actor: "Francesco Acquaroli", role: "Fadda family consigliere and advisor", group: "Fadda family", image: "https://static.wikia.nocookie.net/fargo/images/a/af/Ebal_Violante.jpg/revision/latest?cb=20200916194256" },
        { id: "s4-constant-calamita", name: "Constant Calamita", actor: "Gaetano Bruno", role: "Fadda family hitman", group: "Fadda family", image: "https://static.wikia.nocookie.net/fargo/images/7/7c/Constant_Calamita.jpg/revision/latest?cb=20200916194104" },
        { id: "s4-rabbi-milligan", name: "Rabbi Milligan", actor: "Ben Whishaw", role: "Twice-traded enforcer who defects to protect Satchel", group: "Fadda family", image: "https://static.wikia.nocookie.net/fargo/images/f/f0/Rabbi_Milligan.jpg/revision/latest?cb=20200916194148" },
        { id: "s4-oraetta-mayflower", name: "Oraetta Mayflower", actor: "Jessie Buckley", role: "Serial-killer nurse, the 'Angel of Mercy'", group: "Independent", image: "https://static.wikia.nocookie.net/fargo/images/c/ca/Oraetta_Mayflower.jpg/revision/latest?cb=20200916194950" },
        { id: "s4-ethelrida-smutny", name: "Ethelrida Pearl Smutny", actor: "E'myri Crutchfield", role: "Bright teenage narrator of the season", group: "Smutny family", image: "https://static.wikia.nocookie.net/fargo/images/7/76/Ethelrida_Pearl_Smutney.jpg/revision/latest?cb=20200916194712" },
        { id: "s4-dibrell-smutny", name: "Dibrell Smutny", actor: "Anji White", role: "Ethelrida's mother; co-owns the family funeral home", group: "Smutny family", image: "https://static.wikia.nocookie.net/fargo/images/b/bc/Dibrell_Smutney.jpg/revision/latest?cb=20200916194601" },
        { id: "s4-thurman-smutny", name: "Thurman Smutny", actor: "Andrew Bird", role: "Ethelrida's father; mortician indebted to Loy Cannon", group: "Smutny family", image: "https://static.wikia.nocookie.net/fargo/images/2/22/Thurman_Smutney.jpg/revision/latest?cb=20200916194438" },
        { id: "s4-zelmare-roulette", name: "Zelmare Roulette", actor: "Karen Aldridge", role: "Escaped convict; Dibrell's sister and Ethelrida's aunt", group: "Smutny family", image: "https://static.wikia.nocookie.net/fargo/images/d/dd/ZelmareRoulette.png/revision/latest?cb=20201108160945" },
        { id: "s4-swanee-capps", name: "Swanee Capps", actor: "Kelsey Asbille", role: "Outlaw and Zelmare's partner and girlfriend", group: "Independent", image: "https://static.wikia.nocookie.net/fargo/images/a/aa/Swanee.jpg/revision/latest?cb=20201009035741" },
        { id: "s4-deafy-wickware", name: "Dick 'Deafy' Wickware", actor: "Timothy Olyphant", role: "Mormon U.S. Marshal hunting Zelmare and Swanee", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/2/24/Dick_Wickware_in_Season_4%2C_Episode_4.jpg/revision/latest?cb=20201012080004" },
        { id: "s4-odis-weff", name: "Odis Weff", actor: "Jack Huston", role: "Corrupt, OCD-afflicted Kansas City police detective", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/6/64/Odis_Weff_in_Season_4%2C_Episode_2.jpg/revision/latest?cb=20200929190936" }
      ],
      connections: [
        { source: "s4-loy-cannon", target: "s4-josto-fadda", label: "rival crime boss" },
        { source: "s4-loy-cannon", target: "s4-donatello-fadda", label: "swapped sons with" },
        { source: "s4-loy-cannon", target: "s4-satchel-cannon", label: "gave up his son" },
        { source: "s4-donatello-fadda", target: "s4-rabbi-milligan", label: "traded son" },
        { source: "s4-loy-cannon", target: "s4-doctor-senator", label: "trusted advisor" },
        { source: "s4-loy-cannon", target: "s4-omie-sparkman", label: "enforcer" },
        { source: "s4-loy-cannon", target: "s4-leon-bittle", label: "lieutenant" },
        { source: "s4-loy-cannon", target: "s4-buel-cannon", label: "married to" },
        { source: "s4-loy-cannon", target: "s4-lemuel-cannon", label: "father of" },
        { source: "s4-josto-fadda", target: "s4-gaetano-fadda", label: "brother / rival" },
        { source: "s4-josto-fadda", target: "s4-donatello-fadda", label: "son and successor" },
        { source: "s4-josto-fadda", target: "s4-ebal-violante", label: "consigliere" },
        { source: "s4-gaetano-fadda", target: "s4-constant-calamita", label: "loyal hitman" },
        { source: "s4-josto-fadda", target: "s4-oraetta-mayflower", label: "lover" },
        { source: "s4-oraetta-mayflower", target: "s4-donatello-fadda", label: "poisons / kills" },
        { source: "s4-constant-calamita", target: "s4-doctor-senator", label: "shoots dead" },
        { source: "s4-zelmare-roulette", target: "s4-loy-cannon", label: "stabs to death" },
        { source: "s4-zelmare-roulette", target: "s4-swanee-capps", label: "partner / girlfriend" },
        { source: "s4-zelmare-roulette", target: "s4-dibrell-smutny", label: "sister of" },
        { source: "s4-zelmare-roulette", target: "s4-ethelrida-smutny", label: "aunt of" },
        { source: "s4-deafy-wickware", target: "s4-zelmare-roulette", label: "hunts" },
        { source: "s4-deafy-wickware", target: "s4-swanee-capps", label: "hunts" },
        { source: "s4-odis-weff", target: "s4-deafy-wickware", label: "shoots" },
        { source: "s4-gaetano-fadda", target: "s4-odis-weff", label: "shoots dead" },
        { source: "s4-loy-cannon", target: "s4-odis-weff", label: "bribes" },
        { source: "s4-josto-fadda", target: "s4-odis-weff", label: "bribes" },
        { source: "s4-thurman-smutny", target: "s4-loy-cannon", label: "indebted to" },
        { source: "s4-thurman-smutny", target: "s4-dibrell-smutny", label: "married to" },
        { source: "s4-ethelrida-smutny", target: "s4-oraetta-mayflower", label: "suspects / blackmails" },
        { source: "s4-rabbi-milligan", target: "s4-satchel-cannon", label: "protects / mentors" },
        { source: "s4-rabbi-milligan", target: "s4-loy-cannon", label: "defects to" }
      ]
    },
    {
      season: 5,
      title: "Season Five",
      year: "2023",
      blurb: "In 2019, across Minnesota and North Dakota, a housewife's hidden past comes hunting her.",
      characters: [
        { id: "s5-dorothy-lyon", name: "Dorothy \"Dot\" Lyon", actor: "Juno Temple", role: "Midwestern housewife hiding a violent past as Nadine Tillman", group: "Lyon family", image: "https://static.wikia.nocookie.net/fargo/images/8/84/Dot_Lyon.jpg/revision/latest?cb=20231029191140" },
        { id: "s5-wayne-lyon", name: "Wayne Lyon", actor: "David Rysdahl", role: "Dot's mild-mannered husband, a car salesman", group: "Lyon family", image: "https://static.wikia.nocookie.net/fargo/images/e/e7/Wayne_Lyon.jpg/revision/latest?cb=20231029192414" },
        { id: "s5-lorraine-lyon", name: "Lorraine Lyon", actor: "Jennifer Jason Leigh", role: "Ruthless debt-collection CEO and Dot's mother-in-law", group: "Lyon family", image: "https://static.wikia.nocookie.net/fargo/images/3/3f/Lorraine_Lyon.jpg/revision/latest?cb=20231029191620" },
        { id: "s5-scotty-lyon", name: "Scotty Lyon", actor: "Sienna King", role: "Dot and Wayne's young daughter", group: "Lyon family", image: null },
        { id: "s5-wink-lyon", name: "Wink Lyon", actor: "Jan Bos", role: "Lorraine's husband and Wayne's father", group: "Lyon family", image: null },
        { id: "s5-danish-graves", name: "Danish Graves", actor: "Dave Foley", role: "Lorraine's in-house attorney and loyal fixer", group: "Lyon family", image: "https://static.wikia.nocookie.net/fargo/images/3/38/Danish_Graves.jpg/revision/latest?cb=20231029193004" },
        { id: "s5-roy-tillman", name: "Roy Tillman", actor: "Jon Hamm", role: "Tyrannical North Dakota sheriff and the season's main villain", group: "Tillman family", image: "https://static.wikia.nocookie.net/fargo/images/f/f1/Roy_Tillman.jpg/revision/latest?cb=20231029191416" },
        { id: "s5-gator-tillman", name: "Gator Tillman", actor: "Joe Keery", role: "Roy's loyal son and deputy", group: "Tillman family", image: "https://static.wikia.nocookie.net/fargo/images/0/0c/Gator-Tillman.jpg/revision/latest?cb=20240205230928" },
        { id: "s5-karen-tillman", name: "Karen Tillman", actor: "Rebecca Liddiard", role: "Roy's third wife at the Tillman Ranch", group: "Tillman family", image: null },
        { id: "s5-linda-tillman", name: "Linda Tillman", actor: "Kari Matchett", role: "Roy's first wife and Gator's mother", group: "Tillman family", image: null },
        { id: "s5-ole-munch", name: "Ole Munch", actor: "Sam Spruell", role: "Mysterious, centuries-old Welsh sin-eater hired as a kidnapper", group: "Independent", image: "https://static.wikia.nocookie.net/fargo/images/7/76/Ole_Munch.jpg/revision/latest?cb=20231029192900" },
        { id: "s5-witt-farr", name: "Whitley \"Witt\" Farr", actor: "Lamorne Morris", role: "North Dakota state trooper who helps Dot", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/c/c5/Witt_Farr.jpg/revision/latest?cb=20231029192644" },
        { id: "s5-indira-olmstead", name: "Indira Olmstead", actor: "Richa Moorjani", role: "Scandia deputy with debt troubles", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/f/f5/Indira_Olmstead.jpg/revision/latest?cb=20231029192755" },
        { id: "s5-lars-olmstead", name: "Lars Olmstead", actor: "Lukas Vrabel", role: "Indira's freeloading, debt-ridden husband", group: "Law enforcement", image: "https://static.wikia.nocookie.net/fargo/images/6/6c/FotoJet-2023-01-05T152508.470-1200x900.jpg/revision/latest?cb=20231230025301" }
      ],
      connections: [
        { source: "s5-dorothy-lyon", target: "s5-wayne-lyon", label: "married to" },
        { source: "s5-dorothy-lyon", target: "s5-scotty-lyon", label: "mother of" },
        { source: "s5-wayne-lyon", target: "s5-scotty-lyon", label: "father of" },
        { source: "s5-lorraine-lyon", target: "s5-wayne-lyon", label: "mother of" },
        { source: "s5-wink-lyon", target: "s5-wayne-lyon", label: "father of" },
        { source: "s5-lorraine-lyon", target: "s5-wink-lyon", label: "married to" },
        { source: "s5-lorraine-lyon", target: "s5-dorothy-lyon", label: "mother-in-law of" },
        { source: "s5-lorraine-lyon", target: "s5-danish-graves", label: "employs as attorney" },
        { source: "s5-roy-tillman", target: "s5-dorothy-lyon", label: "ex-husband of" },
        { source: "s5-roy-tillman", target: "s5-gator-tillman", label: "father of" },
        { source: "s5-roy-tillman", target: "s5-karen-tillman", label: "married to (3rd wife)" },
        { source: "s5-roy-tillman", target: "s5-linda-tillman", label: "ex-husband of (1st wife)" },
        { source: "s5-linda-tillman", target: "s5-gator-tillman", label: "mother of" },
        { source: "s5-gator-tillman", target: "s5-dorothy-lyon", label: "hunts to capture" },
        { source: "s5-ole-munch", target: "s5-dorothy-lyon", label: "hired to kidnap" },
        { source: "s5-roy-tillman", target: "s5-ole-munch", label: "hires as kidnapper" },
        { source: "s5-ole-munch", target: "s5-gator-tillman", label: "seeks revenge on" },
        { source: "s5-witt-farr", target: "s5-dorothy-lyon", label: "protects" },
        { source: "s5-indira-olmstead", target: "s5-dorothy-lyon", label: "investigates case of" },
        { source: "s5-indira-olmstead", target: "s5-witt-farr", label: "fellow officer of" },
        { source: "s5-indira-olmstead", target: "s5-lars-olmstead", label: "married to" },
        { source: "s5-indira-olmstead", target: "s5-lorraine-lyon", label: "later works for" },
        { source: "s5-danish-graves", target: "s5-roy-tillman", label: "negotiates against" },
        { source: "s5-lorraine-lyon", target: "s5-roy-tillman", label: "ruins via debt" }
      ]
    }
  ]
};
